# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

description: "Generate GitHub PR review comments using Azure Open AI"

defaultTest:
  options:
    # Used for grading
    provider: file://providers/provider-gpt4o.yaml

prompts:
  - raw: file://./prompts/review.json
    label: development-o1
    config:
      response_format: file://./prompts/review-format.json

providers:
  - id: file://providers/provider-o1.yaml
    prompts:
      - development-o1

tests:
  - vars:
      commitMessage: "Add subtract method to calculator"
      diff: file://./prompts/review-1.diff
    description: "Comment on use of any"
    options:
      # Parse the JSON before all assertions
      transform: JSON.parse(output)
    assert:
      - type: is-json
        value:
          {
            "required": ["comments"],
            "type": "object",
            "properties":
              {
                "comments": { "type": "array", "minItems": 1 },
              },
          }
      - type: javascript
        value: |
          output.comments[0].comment.includes("'any'") && output.comments[0].line === 9 && output.comments[0].file === "src/example.ts"
